# This workflow installs dependencies, restores pnpm cache, builds source code, and runs tests using the Node version from .nvmrc
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - uses: pnpm/action-setup@v4
        with:
          version: 10.30.3
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --if-present
      - run: pnpm test
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - uses: pnpm/action-setup@v4
        with:
          version: 10.30.3
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:formatting
